### ISSUE TITLE
Sorting 

### ISSUE THREAD

**Issue by PiRomant** [ColinIanKing/fnotifystat#1]
Could you add sorting by writes?
This would work well with the `-t` parameter.

**Comment by ColinIanKing** [comment]
Good idea. I'll look into this.

**Comment by fanfan70** [comment]
If I understand well the question, you mean filtering by access type (read, write, ...) ?
In any case it would be very handy to nail down writes on SSD/SDcard devices that wear out because of numerous unnecessary writes.
Thank you !

**Comment by fanfan70** [comment]
I made a little modification to support filtering by access type; it acts on the display part.
It's probably not accomplished due to probable interactions with other parts (statistics computation), that's why I didn't issue a PR. This is only a suggestion, you'll probably want to validate/modify it.

2 command line options are added :
 -j     filter stats by access type
           argument is one or more of o,c,r,w (open,close,read,write) separated by commas
           access types are combined with logical AND
           e.g. -e o,w will only display files with at least open and write events
-k     same as -j with logical OR

[https://pastebin.com/6d97166Y](url)

Regards!
